name: 🚀 Deploy to Server

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Repository
        uses: actions/checkout@v3
      
      - name: 🔑 Setup SSH & Deploy
        run: |
          # Setup SSH Key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

          # Connect & Run Deployment Commands
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/html  # Change to your project directory
            git pull origin main  # Pull the latest changes
            
            # Cleanup
            exit
          EOF

      - name: ✅ Deployment Successful
        run: echo "Deployment completed successfully!"