name: 🚀 Deploy to Server

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secrets
        run: |
          echo "Checking if secrets are set..."
          echo "PROJECT_PATH length: ${#PROJECT_PATH}"
          echo "PROJECT_PATH 1 ${{ secrets.PROJECT_PATH }} "
        env:
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
    